version: '2'
volumes:
  powerdns-data: {}
  powerdns-admin-data: {}
  pihole-data: {}
services:
  powerdns-admin:
    image: ngoduykhanh/powerdns-admin:latest
    restart: always
    privileged: true
    networks:
      - web
    ports:
      - 9191:80
    volumes:
      - powerdns-admin-data:/data
    environment:
      - SECRET_KEY="secretkey"
#      - SQLALCHEMY_TRACK_MODIFICATIONS=
#    'SQLALCHEMY_DATABASE_URI=
#    'MAIL_SERVER=
#    'MAIL_PORT=
#    'MAIL_DEBUG=
#    'MAIL_USE_TLS',
#    'MAIL_USE_SSL',
#    'MAIL_USERNAME',
#    'MAIL_PASSWORD',
#
#    'MAIL_DEFAULT_SENDER',
    depends_on:
      - powerdns
    container_name: powerdns-admin


  powerdns:
    build:
      context: .
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
      - "80:8080"
    environment:
      - TIMEZONE=Europe/Berlin
      - CUSTOM_DNS="8.8.8.8;8.8.4.4;[2001:4860:4860::8888];[2001:4860:4860::8844]"
      - ENABLE_ADBLOCK=true
      - API_KEY=my-awesome-api-key
      - CRONTAB_TIME="0 10 * * *"
    volumes:
     - powerdns-data:/srv/data
    depends_on:
      - hostname
      - hetzner-ddns
    container_name: powerdns
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
#      io.balena.features.journal-logs: '1'
      io.balena.features.supervisor-api: '1'

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname:latest
    restart: unless-stoped
#   privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: powerdns

  hetzner-ddns:
    image: kutzilla/hetzner-ddns:latest
    container_name: hetzner-ddns
    network_mode: host
    privileged: true
    networks:
      - web
    environment:
      # Record Type A for IPv4
      RECORD_TYPE: A
      # Record Type AAAA for IPv6
      API_TOKEN: "UZgSPSuRL4Uvz3be2UdST5y2XWlUhOec"
      ZONE_NAME: "mioga.eu"
      # The name of the DNS-record that DDNS updates should be applied to. 
      # This could be sub if you like to update the subdomain sub.example.com of example.com. 
      # The default value is @
      RECORDE_NAME: "dev"
      # The cron expression of the DDNS update interval. The default is every 5 minutes - */5 * * * *
#     CRON_EXPRESSION: 
    restart: always
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
#      io.balena.features.journal-logs: '1'
      io.balena.features.supervisor-api: '1'